"""date

Revision ID: ec08229247a6
Revises: 2024_11_06_upgrade_database
Create Date: 2024-11-06 03:01:06.128257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2024_11_06_date'
down_revision: Union[str, None] = '2024_11_06_upgrade_database'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
